### PR TITLE
handle groups of size 1 in grab_psiFUN's

### PR DESCRIPTION
**Pull request by BarkleyBG**
This may not handle groups of size 1 in `grab_psiFun.mermod()` but it should be a simple workaround for the gee and glm cases.

### CODE REVIEW

**Comment by BarkleyBG** [comment]
I'm not really familiar with codecov. I'll admit I didn't fully vet the geeglm solution; did break something or fail to pass a test?

Also, once these are implemented I guess the version should be bumped to 1.0.3001 or something.

**Comment by bsaul** [comment]
I'm wondering if rather than `D <- apply(X, ...)`, we should use `vapply(X, FUN, FUN.VALUE = matrix(ncol = n, nrow = n)`, so that the dimension and type of object returned is guaranteed to be a matrix. That way we don't need to later check the dimensions of `D`.

Also, it appears that the check you added fails. [See the travis-ci report](https://travis-ci.org/bsaul/geex/builds/274218366?utm_source=github_status&utm_medium=notification):

```
  testthat results ================================================================
  OK: 77 SKIPPED: 0 FAILED: 1
  1. Error: estimate equations obtains correct values for parameters and standard errors  (@test_grab_eeFUN_glm.R#28) 
```

Can you double check the test?

**Comment by BarkleyBG** [comment]
It turns out `is.atomic(my_matrix)=TRUE`; i thought it would return false. 

I couldn't get the `vapply()` solution to work out, so I hope you don't mind this hack. Do you want me to squash this patch into a single commit or anything?

**Comment by bsaul** [comment]
Can you push this to the `develop` branch rather than `master`? Then I'll
take a closer look at the vapply option.

On Mon, Sep 18, 2017 at 10:25 AM, Brian G. Barkley <notifications@github.com

**Comment by BarkleyBG** [comment]
done

**Pull request merged**
